Add IsBalanced function
VRublevski/balanced-parentheses pull request #1
Opened 2021-01-04 11:25 UTC by VRublevski

2021-01-04 14:34 UTC, papahmsolo requested changes
Tests look great!
Let's refactor the logic a little bit.

2021-01-04 14:34 UTC, papahmsolo commented on bracket/bracket.go
> +	}
Brackets map does not change, so we can make it global and don't create an instance of the map on each `IsBalanced` call.

2021-01-04 14:34 UTC, papahmsolo commented on bracket/bracket.go
> +		}
We can reverse this condition and handle cases when we encounter opening or closed brackets.

2021-01-04 14:34 UTC, papahmsolo commented on bracket/bracket.go
> +}
We can explicitly check in the loop if `v` is one of the opening or closing brackets, can't we? Thus we can get rid of this function, which is great :)

2021-01-04 15:09 UTC, VRublevski commented on bracket/bracket.go
> +	}
@papahmsolo That was the first idea, but later it seemed like just a few if any functions would require this global variable, so I decided to make it local to `IsBalanced` function. Now it's a global variable.

2021-01-04 15:15 UTC, VRublevski commented on bracket/bracket.go
> +		}
@papahmsolo I wanted to make as little nesting of if constructs as possible, so I used this condition. I followed your advice. Maybe it's more clear what kind of symbol the rest of the code processes now.

2021-01-04 15:21 UTC, VRublevski commented on bracket/bracket.go
> +}
@papahmsolo I thought that this checking would be used by many other routines, so I made it a function. It looked like it's more clear for what it checks with explicit function name. I got rid of it.

2021-01-04 15:51 UTC, papahmsolo requested changes
Moving on :)

2021-01-04 15:51 UTC, papahmsolo commented on bracket/bracket.go
> +			} else {
We enter `if` only for opening brackets and `else` for only closing, can we make conditions for ifs simpler? We won't need to nest them then.

2021-01-04 15:51 UTC, papahmsolo commented on bracket/bracket.go
> +}
I think we can come up with a better name, why is it called `openingBrackets`? It's more of a brackets mapping, which matches which.

2021-01-04 17:24 UTC, VRublevski commented on bracket/bracket.go
> +}
@papahmsolo One day I will use not awkward and self-explaining variable names.

2021-01-04 17:26 UTC, VRublevski commented on bracket/bracket.go
> +			} else {
@papahmsolo I brought up logic into separate cases for current symbol.

2021-01-04 17:29 UTC, VRublevski commented on bracket/bracket.go
> +				}
@papahmsolo As I've brought up code into cases it become clear for me that they can be combined.

2021-01-05 06:50 UTC, papahmsolo requested changes
Looks very good!

2021-01-05 06:50 UTC, papahmsolo commented on bracket/bracket.go
> +		}
If we enter the first `if` should we check this condition after that `strings.ContainsRune("({[", v)`?

2021-01-05 06:50 UTC, papahmsolo commented on bracket/bracket.go
> +			openingBracket := bracketMap[v]
We probably don't need this variable, we can access the map in the `if`

2021-01-05 06:50 UTC, papahmsolo commented on bracket/bracket.go
> +		if strings.ContainsRune(")}]", v) {
Can we check if `v` is one of the closing brackets without `strings.ContainsRune`?

2021-01-05 08:23 UTC, VRublevski commented on bracket/bracket.go
> +		}
@papahmsolo No, we shouldn't. Also we can't omit it with `else`, because there are non-bracket symbols, so I use `continue` now.

2021-01-05 08:26 UTC, VRublevski commented on bracket/bracket.go
> +			openingBracket := bracketMap[v]
@papahmsolo Yes, I've removed it.

2021-01-05 08:26 UTC, VRublevski commented on bracket/bracket.go
> +		if strings.ContainsRune(")}]", v) {
@papahmsolo Yes, it's one of the closing brackets if there's a pair for it in the `bracketMap`. Now I use this approach.

2021-01-05 12:06 UTC, papahmsolo commented on bracket/bracket.go
> +		}
Looks like `continue` is here server the purpose of `else`, why no using it then? :)

2021-01-05 12:10 UTC, papahmsolo requested changes
Cool, let's refactor it a little more!

2021-01-05 12:10 UTC, papahmsolo commented on bracket/bracket.go
> +		}
We can eliminate the `ContainsRune()` call by just checking if `v` is one of the opening brackets?

2021-01-05 12:37 UTC, VRublevski commented on bracket/bracket.go
> +		}
@papahmsolo Now I understand what I was supposed to do, and use `if else`.

2021-01-05 12:40 UTC, VRublevski commented on bracket/bracket.go
> +		}
@papahmsolo I eliminated this call. I think that explicit check can assist in debugging producing less number of stack frames.

2021-01-05 12:44 UTC, papahmsolo commented on bracket/bracket.go
> +		}
Cool, I guess, it'd be much cleaner to use a `switch` here with two cases, for opening and closing brackets

2021-01-05 12:45 UTC, papahmsolo requested changes
Let's make a final change and we're ready to move on

2021-01-05 12:47 UTC, papahmsolo commented on bracket/bracket.go
> +		}
@VRublevski readability is of paramount importance, we're not that concerned about performance here

2021-01-05 13:06 UTC, VRublevski commented on bracket/bracket.go
> +		}
@papahmsolo I used a `switch` statement, and discovered something new about it.

2021-01-05 13:11 UTC, papahmsolo commented on bracket/bracket.go
> +			continue
No need for `default` here, we can delete it

2021-01-05 13:11 UTC, papahmsolo requested changes
Way cleaner with the switch, isn't it?

2021-01-05 13:16 UTC, VRublevski commented on bracket/bracket.go
> +			continue
@papahmsolo I deleted the default branch.

2021-01-05 13:19 UTC, merged