Add parentheses web service
VRublevski/balanced-parentheses pull request #2
Opened 2021-01-06 10:55 UTC by VRublevski

2021-01-06 14:49 UTC, papahmsolo requested changes
Not bad! Let's make it a bit better 👍

2021-01-06 14:49 UTC, papahmsolo commented on bracket/bracket.go
> +func NewSequence(n int, tp int) string {
When reading for the first time, it's really difficult to understand what is `tp` for. Meaningful name or explanation in the comment wouldn't harm 👍 
So, let's implement this function so that it returns an arbitrary sequence of brackets of the length n, not only brackets of some type.

2021-01-06 14:49 UTC, papahmsolo commented on bracket/bracket.go
> +)
That's good you know how to use `iota`, but we don't need this for the purpose of this exercise

2021-01-06 14:49 UTC, papahmsolo commented on cmd/server/main.go
> +	}
I think we can combine this into one scenario `invalid n`

2021-01-06 14:49 UTC, papahmsolo commented on cmd/server/main.go
> +	response := generator.Next(s.rnd, roundSeq+curlySeq+squareSeq)
Let's move this business logic outside the http handler, this is something you'd want to in the "NewSequence"

2021-01-06 14:49 UTC, papahmsolo commented on cmd/server/main.go
> +	rnd := rand.New(rand.NewSource(int64(*seedFlag)))
Just a note, we don't have to ask for the seed, we can do something like this
`rand.New(rand.NewSource(time.Now().UnixNano()))`

2021-01-07 12:08 UTC, VRublevski commented on bracket/bracket.go
> +func NewSequence(n int, tp int) string {
@papahmsolo You're right, I should have added a comment. I've got rid of it and now the function returns an arbitrary sequence of brackets.

2021-01-07 12:10 UTC, VRublevski commented on bracket/bracket.go
> +)
@papahmsolo These constants are no longer necessary as I deleted a function that returns sequences of a particular type. So, I've removed them.

2021-01-07 12:11 UTC, VRublevski commented on cmd/server/main.go
> +	}
@papahmsolo Yes, it's much cleaner now.

2021-01-07 12:14 UTC, VRublevski commented on cmd/server/main.go
> +	response := generator.Next(s.rnd, roundSeq+curlySeq+squareSeq)
@papahmsolo I've followed your advice and moved this code to `Next` method of the `Generator` type.

2021-01-07 12:17 UTC, VRublevski commented on cmd/server/main.go
> +	rnd := rand.New(rand.NewSource(int64(*seedFlag)))
@papahmsolo I wanted to have deterministic sequences at first, but then I realized that it's more interesting to have truly random ones. So, I use this approach for creating a new `Source` now.

2021-01-11 12:34 UTC, papahmsolo requested changes
Looks good! Let's also test the generator

2021-01-11 12:34 UTC, papahmsolo commented on cmd/server/main.go
> +		fmt.Fprintln(w, "invalid n")
Let's also say why is it invalid

2021-01-11 12:34 UTC, papahmsolo commented on cmd/server/main.go
> +	h.mu.Unlock()
Not sure why would we want to have a mutex here

2021-01-11 16:01 UTC, papahmsolo requested changes
Looks great, Vald!
Let's simplify the parentheses generation a bit. Do we need a `Generator` type? We're not really configuring it, so a simple func would do.

2021-01-11 17:58 UTC, VRublevski commented
I've made the suggested changes.

2021-01-12 08:46 UTC, papahmsolo requested changes
Well done!

Shouldn't we also write a test for `Generate()`?

2021-01-12 08:46 UTC, papahmsolo commented on bracket/bracket.go
> +	}
A map with sequential integers as keys looks like an array to me :) What do you think?

2021-01-12 08:46 UTC, papahmsolo commented on bracket/bracket.go
> +	builder := strings.Builder{}
String builder is fine, but we can simply use a slice of runes and write brackets to it. We can then easily convert it to a string!

2021-01-12 08:46 UTC, papahmsolo commented on cmd/server/main.go
> +	rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
Let's move this into `Generate` I think it belongs there, not to the handler.

2021-01-12 08:46 UTC, papahmsolo commented on cmd/server/main.go
> +	nParam := req.URL.Query().Get("n")
We already know it's a param, don't we?

2021-01-12 09:52 UTC, VRublevski commented on bracket/bracket.go
> +	}
@papahmsolo Yes, it's a silly mistake. That was a long day :)

2021-01-12 09:54 UTC, VRublevski commented on bracket/bracket.go
> +	builder := strings.Builder{}
@papahmsolo You're right. I only appended runes, so there was no necessity for `strings.Builder`

2021-01-12 10:09 UTC, VRublevski commented on cmd/server/main.go
> +	rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
@papahmsolo I wanted the users of `bracket` package to be able to provide their own random generator by implementing `Source` interface. That was the primary purpose of the `Generator` type. It looked like a greater flexibility. Now I realize that can't give an example of such an application of self-devised random generator to bracket generation facility, aside from convenience of testing. I think that the most common case will be to use some standard `Source` interface implementations, so it's pretty reasonable to do it in the package you provide.

2021-01-12 10:15 UTC, VRublevski commented on cmd/server/main.go
> +	nParam := req.URL.Query().Get("n")
@papahmsolo I needed some temporary name for storing string representation of the parameter. I thought it was a good one. Now I renamed it to `nStr`, but do not know if it's a right choice. It looks like you know the pattern of naming variables which hold query parameters and variables for `map` type.

2021-01-12 18:45 UTC, papahmsolo commented on bracket/bracket.go
> +	}
- Let's come up with a simpler name, it's not a map, technically
- Indices are cool, but do we really need them?

2021-01-12 18:59 UTC, papahmsolo requested changes
Very nice Vlad! 

Test helpers are good when you want to reuse them, but for `Generate()` we use them only once, so we might just want to move the helpers to the test function.

2021-01-12 18:59 UTC, papahmsolo commented on bracket/bracket.go
> +	bracketPairMap = map[rune]rune{
We know it's a map by it's declaration, don't we? But it does not contribute to readability, IMO

2021-01-12 18:59 UTC, papahmsolo commented on bracket/bracket_test.go
> +func assertN(want, got int, t *testing.T) {
`assertLength` would be better, IMO

2021-01-12 18:59 UTC, papahmsolo commented on bracket/bracket_test.go
> +		},
What difference do these tests make with odd and even test cases?

2021-01-12 19:00 UTC, papahmsolo commented on cmd/server/main.go
> +		fmt.Fprintln(w, "invalid n")
Or we can indicate, what we expect. It never does any harm to provide some details

2021-01-12 19:01 UTC, papahmsolo commented on cmd/server/main.go
> +	nParam := req.URL.Query().Get("n")
@VRublevski I think it's fine, let's leave it as is

2021-01-13 08:40 UTC, VRublevski commented on bracket/bracket.go
> +	bracketPairMap = map[rune]rune{
@papahmsolo I just wanted to be consistent with names, there were a variable named `numToBracketMap` which had similar purpose. I renamed all global variables.

2021-01-13 08:42 UTC, VRublevski commented on bracket/bracket_test.go
> +func assertN(want, got int, t *testing.T) {
@papahmsolo Yes, it's clear from that name what is the purpose of the function. I deleted all the test helper functions, so it's no longer a problem.

2021-01-13 08:53 UTC, VRublevski commented on bracket/bracket_test.go
> +		},
@papahmsolo I just wanted to partition all the input space of the function under the test into subsets of objects having specific properties. It's impossible to test the function for all possible inputs and also one may expect that the function will process the input differently based on their properties. So it looks like a good idea for there to be a test case with an object from all the parts of the partitioned space. I was introduced to this idea in a lecture on the Internet.

2021-01-13 15:13 UTC, VRublevski commented on cmd/server/main.go
> +		fmt.Fprintln(w, "invalid n")
@papahmsolo I added a description of valid input to this error message.

2021-01-14 06:08 UTC, papahmsolo requested changes
Final touch and we'll merge it!

2021-01-14 06:08 UTC, papahmsolo commented on bracket/bracket_test.go
> +				switch v {
- just FYI, `continue` is optional, but let's leave it for readability
- no need to convert `v` to a string, `%q` will print the character not unicode point
- it's always good to provide more details in the error message, it's very helpful for debugging. Try to fail the test and see what info you get. We could provide the position of the non-bracket rune along with the generated string (use aslo `%q`)

2021-01-14 08:02 UTC, VRublevski commented on bracket/bracket_test.go
> +				switch v {
@papahmsolo I will follow these advice from now on.

2021-01-14 10:04 UTC, papahmsolo approved these changes
Nice!

2021-01-14 10:04 UTC, merged