Add client implementation with balanced sequence percentage calculation support
VRublevski/balanced-parentheses pull request #3
Opened 2021-01-14 14:29 UTC by VRublevski

2021-01-15 13:00 UTC, papahmsolo requested changes
Cool! It's a good idea to make requests in parallel.

Do we need to keep track of imbalanced bracket sequences? This can simplify things dramatically

2021-01-15 14:49 UTC, VRublevski commented on cmd/client/main.go
> +	portFlag := flag.Int("port", 8000, "port the remote server is listening on")
@papahmsolo Yes, I was thinking of something different, but that's also a misunderstanding.

2021-01-15 14:52 UTC, VRublevski commented on cmd/client/main.go
> +}
@papahmsolo I thought that it's more correct way of constructing URL, but that is very simple, so it's not worth doing.

2021-01-15 14:55 UTC, VRublevski commented on cmd/client/main.go
> +}
@papahmsolo Yes. In the previous version of the program I thought `fetchURL` alone can be reused and `fetchURLs` can't, at least implemented like this. So I decided ti split them.

2021-01-15 14:57 UTC, VRublevski commented
Now a single goroutine is doing the job. Please, leave comments about this version.

2021-01-18 11:20 UTC, papahmsolo requested changes
Looks good!

I guess we can get rid of some lines of code :)

2021-01-18 11:20 UTC, papahmsolo commented on cmd/client/main.go
> +)
Let's think if we need it at all or we can calculate it in the loop?

2021-01-18 11:20 UTC, papahmsolo commented on cmd/client/main.go
> +	}
No need to set it to zero, zero is the default value

2021-01-18 11:20 UTC, papahmsolo commented on cmd/client/main.go
> +	balancedPercentage := make(map[int]int)
Do we also need this map? We can print the results right away

2021-01-18 11:20 UTC, papahmsolo commented on cmd/client/main.go
> +}
We can inline this function into main, can't we? It's just a couple of lines of code

2021-01-18 11:20 UTC, papahmsolo commented on cmd/client/main.go
> +	}
Don't forget to close the body

2021-01-18 12:44 UTC, VRublevski commented on cmd/client/main.go
> +)
@papahmsolo I think that it's easier to apply changes when we're calculating the lengths, and not reading them. So I followed your advice.

2021-01-18 12:49 UTC, VRublevski commented on cmd/client/main.go
> +	}
@papahmsolo I made that to able to `range` loop through the lengths later. Now I realize that it's silly, I got rid of that.

2021-01-18 12:51 UTC, VRublevski commented on cmd/client/main.go
> +}
@papahmsolo I just wanted to give a name to this computation, so that one can understand it at once. It's really simple, so probably there's no need to pollute the namespace. I removed it.

2021-01-18 12:52 UTC, VRublevski commented on cmd/client/main.go
> +	}
@papahmsolo I picked it up :)

2021-01-18 15:26 UTC, papahmsolo requested changes
Very good!

Maybe we don't need the `responses` slice, we'll have to range over it then, but we actually care about the sequence, aren't we?

2021-01-18 15:26 UTC, papahmsolo commented on cmd/client/main.go
> +		length := 2 * i
How about incrementing by two? 💡

2021-01-18 15:26 UTC, papahmsolo commented on cmd/client/main.go
> +		}
Let's not terminate on the first error that occurs when calling the API. I suggest we log the error so that we know about it, but consider the response as an unbalanced sequence.

2021-01-18 15:54 UTC, VRublevski commented on cmd/client/main.go
> +		length := 2 * i
@papahmsolo It's a good idea. We will not have unnecessary intermediate variables then.

2021-01-18 15:57 UTC, VRublevski commented on cmd/client/main.go
> +		}
@papahmsolo I made appropriate changes for this.

2021-01-19 09:58 UTC, VRublevski commented on cmd/client/main.go
> +	balancedPercentage := make(map[int]int)
@papahmsolo I removed it.

2021-01-19 10:00 UTC, papahmsolo requested changes
Looks very good!

- Let's add some detail on how to use this module to get the report (run server, run client)
- Let's think of a better name for `client`, what its actual purpose is?

2021-01-19 10:00 UTC, papahmsolo commented on cmd/client/main.go
> +	}
Let's also check if we got `200` and return an error otherwise

2021-01-19 10:49 UTC, VRublevski commented on cmd/client/main.go
> +	}
@papahmsolo I handle the status code now.

2021-01-19 12:49 UTC, papahmsolo requested changes
Cool!

Let's resolve the conflict and we can merge it and move on to a concurrent version

2021-01-19 12:49 UTC, papahmsolo commented on cmd/report/main.go
> +	}
I think `err` is `nil` at this point, you might want to create an error yourself

2021-01-19 13:04 UTC, VRublevski commented on cmd/report/main.go
> +	}
@papahmsolo I fixed that.

2021-01-19 14:59 UTC, papahmsolo approved these changes
Superb!

2021-01-19 14:59 UTC, merged